- name: "Set user password"
  hosts: all
  become: yes

  vars  :
    username: "admin"
    password: "xeiBoo4ahL9ohh"

  tasks:
    - user: name={{ username }} password={{ password | password_hash('sha512') }}
    - debug: msg="Password for user {{ username }} has been set"
